name: Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r af/requirements.txt
          pip install -r nef/requirements.txt

      - name: Run Tests
        run: python -m unittest */test*.py
